name: 'dbt_tileset'
version: '1.0.0'
profile: 'dbt_tileset'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_tileset:
    staging:
      +schema: tileset_silver
      +materialized: view
    intermediate:
      +schema: tileset_silver
      +materialized: ephemeral
    marts:
      +schema: tileset_gold
      +materialized: table

vars:
  start_date: '2020-01-01'

seeds:
  dbt_tileset:
    regional_sales:
      +schema: tileset_bronze
      +column_types:
        region: string
        sale_month: string
        product_line: string
        units_sold: integer
        revenue: double